### ISSUE TITLE
Deploy failed when ansible version upgrade

### ISSUE THREAD

**Issue by brightben** [mJace/x-k8s#16]
As title, deploy failed when I use ansible 2.8. Please lock deploy node ansible version to 2.7.8.

**Comment by mJace** [comment]
TODO:
Edit requirements.txt in root repo dir to fix this...

**Comment by mJace** [comment]
https://github.com/kubernetes-sigs/kubespray/issues/4778

**Comment by mJace** [comment]
https://github.com/mJace/x-k8s/commit/2059b8f67a39cee00b0b8cad4490468927e947e6

**Comment by mJace** [comment]
Tested successfully with a new container as deploy node and 2 clean ubuntu 18 machine as k8s nodes.
