### ISSUE TITLE
After install k8x, the container created by docker cant resolve DNS.

### ISSUE THREAD

**Issue by mJace** [mJace/x-k8s#18]
After install k8x, the container created by docker cant resolve DNS.

Is this kubespray's problem or x-k8s?

**Comment by mJace** [comment]
On ubuntu 18, DNS is configured in `cat /run/systemd/resolve/resolv.conf`  
However, Kubespray will configure the docker dns setting according to `cat /etc/resolv.conf` 
and make the continaer started by docker failed during Dns resolving.

**Comment by mJace** [comment]
https://github.com/kubernetes-sigs/kubespray/issues/4808

**Comment by mJace** [comment]
安裝x-k8s之前
`ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf`
讓kubespray設定正確的dns

**Comment by mJace** [comment]
TODO: Set up a ansible role to setting this before install docker/k8s installation

**Comment by lovenery** [comment]
I reset K8s with kubespray (v2.11.0) on my machine, and the container created by docker still cannot resolve DNS.

Afterwards,
I remove docker (apt autoremove) and install it ([install ref](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository)).
It works!

The above situation is suitable when you want to turn back from k8s to container.

**Comment by mJace** [comment]
> I reset K8s with kubespray (v2.11.0) on my machine, and the container created by docker still cannot resolve DNS.
> 
> Afterwards,
> I remove docker (apt autoremove) and install it ([install ref](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository)).
> It works!
> 
> The above situation is suitable when you want to turn back from k8s to container.

@lovenery 
Create related issue at https://github.com/ITRI-ICL-Peregrine/x-k8s
